name: ci/cd book-manger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: setup docker
          uses: docker/setup-buildx-action@v2
          
        - name: running docker compose
          run: |
            docker compose up --build -d
            
        - name: check application
          run: |
            docker ps 
            docker exec -it book-manager-project-tomcat-1 bash ls -l /webapps/ROOT.war || true 
            docker excecbook-manager-project-tomcat-1 curl -v http://localhost:8080 || exit 1
        - name: stop docker compose
          run: |
            docker compose down
    
    
    
    
