name: ci/cd book-manger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: setup docker
          uses: docker/setup-buildx-action@v2
        - name: install docker-compose
          run: |
            sudo apt-get update
            sudo apt-get install docker-compose-plugin -y
        - name: running docker-compose
          run: |
            docker-compose -d --build
        - name: check application
          run: |
            docker ps 
            docker excec book-manger_app_1 curl -v http://localhost:8000
        - name: stop docker-compose
          run: |
            docker-compose down
    
    
    
    
